# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SelectCF_getuw_lasso <- function(ds_, wbounds_, max_iter, init_random, silent, warm_start) {
    .Call('_SelectCF_SelectCF_getuw_lasso', PACKAGE = 'SelectCF', ds_, wbounds_, max_iter, init_random, silent, warm_start)
}

SelectCF_getuw_lasso_lagrange <- function(ds_, lambdas_, max_iter, init_random, silent, warm_start) {
    .Call('_SelectCF_SelectCF_getuw_lasso_lagrange', PACKAGE = 'SelectCF', ds_, lambdas_, max_iter, init_random, silent, warm_start)
}

SelectCF_getuw_fl <- function(ds_, lambda1s_, lambda2s_, max_iter, init_random, silent) {
    .Call('_SelectCF_SelectCF_getuw_fl', PACKAGE = 'SelectCF', ds_, lambda1s_, lambda2s_, max_iter, init_random, silent)
}

SelectCF_getuw_ssl <- function(ds_, penalty_, lambda1, lambda0s_, theta, aa, bb, eps, max_iter, init_random, silent, warm_start) {
    .Call('_SelectCF_SelectCF_getuw_ssl', PACKAGE = 'SelectCF', ds_, penalty_, lambda1, lambda0s_, theta, aa, bb, eps, max_iter, init_random, silent, warm_start)
}

SelectCF_get_crit <- function(ds_, w_) {
    .Call('_SelectCF_SelectCF_get_crit', PACKAGE = 'SelectCF', ds_, w_)
}

SelectCF_get_u <- function(ds_, w_) {
    .Call('_SelectCF_SelectCF_get_u', PACKAGE = 'SelectCF', ds_, w_)
}

get_outliers_from_dist <- function(dist_, loop_k, loop_lambda, loop_threshold, outlier_on) {
    .Call('_SelectCF_get_outliers_from_dist', PACKAGE = 'SelectCF', dist_, loop_k, loop_lambda, loop_threshold, outlier_on)
}

get_outliers_from_ds <- function(ds_, loop_k, loop_lambda, loop_threshold, outlier_on) {
    .Call('_SelectCF_get_outliers_from_ds', PACKAGE = 'SelectCF', ds_, loop_k, loop_lambda, loop_threshold, outlier_on)
}

multfun <- function(x_) {
    .Call('_SelectCF_multfun', PACKAGE = 'SelectCF', x_)
}

distfun <- function(x_) {
    .Call('_SelectCF_distfun', PACKAGE = 'SelectCF', x_)
}

